receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    limit_mib: 512
    check_interval: 1s
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  # Экспонируем метрики для скрейпа Prometheus на :8889 в OpenMetrics (с exemplars)
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      job: "otel-collector"
    enable_open_metrics: true

  # Отправляем трейсы в Jaeger (OTLP gRPC)
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  debug:
    verbosity: normal

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger, debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, debug]
