receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    limit_mib: 512
    check_interval: 1s

exporters:
  # Экспорт трейсов в Jaeger через OTLP
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  # Экспорт метрик в Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: "api"
    enable_open_metrics: true

  # ЗАМЕНИЛ logging на debug
  debug:
    verbosity: detailed

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  telemetry:
    logs:
      level: "info"
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger, debug]  # Исправил имя экспортера

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, debug]   # Исправил имя экспортера