receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 512

exporters:
  # Prometheus с правильным синтаксисом
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "aspnetcore"
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true
    # Exemplars включаются автоматически при enable_open_metrics: true

  # Jaeger для трейсов
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  # Для отладки
  debug:
    verbosity: basic

service:
  telemetry:
    logs:
      level: "info"
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, debug]

  extensions: []